/* 
 *  Copyright © 2024 Eduardo Vindas Cordoba. All rights reserved.
 *  
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 *
 */
package com.aeongames.stegsolveplus.ui;

import com.aeongames.edi.utils.visual.ImageScaleComponents;
import com.aeongames.edi.utils.visual.Panels.TranslucentImagedPanel;

/**
 *
 * @author Eduardo Vindas
 */
public class GlassFileDnDPanel extends javax.swing.JPanel {

    /**
     * Creates new form GlassFileDnDpanel
     */
    public GlassFileDnDPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        var image = MainFrame.class.getResource("/com/aeongames/stegsolveplus/ui/Drop.png") == null
        ? null : new javax.swing.ImageIcon(
            MainFrame.class.getResource("/com/aeongames/stegsolveplus/ui/Drop.png"));
        translucentImagedPanel1 = new TranslucentImagedPanel(image.getImage());
        translucentImagedPanel1.setBackgroundPolicy(ImageScaleComponents.SCALE_SMALL_ONLY);

        setOpaque(false);

        translucentImagedPanel1.setArcHeight(100);
        translucentImagedPanel1.setArcWidth(100);

        javax.swing.GroupLayout translucentImagedPanel1Layout = new javax.swing.GroupLayout(translucentImagedPanel1);
        translucentImagedPanel1.setLayout(translucentImagedPanel1Layout);
        translucentImagedPanel1Layout.setHorizontalGroup(
            translucentImagedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        translucentImagedPanel1Layout.setVerticalGroup(
            translucentImagedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(translucentImagedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(translucentImagedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aeongames.edi.utils.visual.Panels.TranslucentImagedPanel translucentImagedPanel1;
    // End of variables declaration//GEN-END:variables
}
