/* 
 *  Copyright © 2024 Eduardo Vindas Cordoba. All rights reserved.
 *  
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 *
 */
package com.aeongames.stegsolveplus.ui;

import com.aeongames.edi.utils.visual.ImageScaleComponents;
import com.aeongames.edi.utils.visual.Panels.TranslucentImagedPanel;

/**
 *
 * @author Eduardo Vindas
 */
public class GlassFileDnDPanel extends javax.swing.JPanel {

    private short Alphalevel;
    private float ImageAlpha;
    private DragAndDrop dndHelper;

    /**
     * Creates new form GlassFileDnDpanel
     */
    public GlassFileDnDPanel(DragAndDrop helper) {
        initComponents();
        dndHelper=helper;
    }
    

    /**
     * this sets the panel to be visible HOWEVER fully transparent.
     *
     * @param Invisible
     */
    public void setInvisible(boolean Invisible) {
        var alpha = translucentImagedPanel1.getpanelAlpha();
        if (alpha != 0) {
            Alphalevel = alpha;
        }
        var alphaimg = translucentImagedPanel1.getImageAlphaLevel();
        if (alphaimg != 0) {
            ImageAlpha = alphaimg;
        }
        translucentImagedPanel1.setPanelTrasparency(Invisible ? 0 : Alphalevel);
        translucentImagedPanel1.setImageTrasparency(Invisible ? 0 : ImageAlpha);
    }

    @Override
    public void removeNotify() {
        dndHelper.UnRegisterTarget(this);
        super.removeNotify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        var image = MainFrame.class.getResource("/com/aeongames/stegsolveplus/ui/Drop.png") == null
        ? null : new javax.swing.ImageIcon(
            MainFrame.class.getResource("/com/aeongames/stegsolveplus/ui/Drop.png"));
        translucentImagedPanel1 = new TranslucentImagedPanel(image.getImage());
        translucentImagedPanel1.setBackgroundPolicy(ImageScaleComponents.SCALE_SMALL_ONLY);

        setOpaque(false);

        translucentImagedPanel1.setBackground(new java.awt.Color(255, 255, 0));
        translucentImagedPanel1.setArcHeight(100);
        translucentImagedPanel1.setArcWidth(100);

        javax.swing.GroupLayout translucentImagedPanel1Layout = new javax.swing.GroupLayout(translucentImagedPanel1);
        translucentImagedPanel1.setLayout(translucentImagedPanel1Layout);
        translucentImagedPanel1Layout.setHorizontalGroup(
            translucentImagedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        translucentImagedPanel1Layout.setVerticalGroup(
            translucentImagedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(translucentImagedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(translucentImagedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aeongames.edi.utils.visual.Panels.TranslucentImagedPanel translucentImagedPanel1;
    // End of variables declaration//GEN-END:variables
}
